name: Apolinario

on:
  schedule:
    - cron: '0 */5 * * *'  # Executa a cada 5 horas
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 horas

    steps:
      - name: Checkout repo (teste)
        uses: actions/checkout@v4

      - name: Set hostname
        run: sudo hostnamectl set-hostname apolinario

      - name: Instalar dependências básicas
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Restaurar último backup do repo
        run: |
          if [ -f backups/latest.zip ]; then
            unzip -o backups/latest.zip -d /
            echo "✅ Backup restaurado do repositório"
          else
            echo "⚠️ Nenhum backup encontrado no repo!"
          fi

      - name: Criar usuário apolinario
        run: |
          if ! id -u apolinario >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash apolinario
            echo "apolinario:apolinario" | sudo chpasswd
            sudo usermod -aG sudo apolinario
            echo "apolinario ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/apolinario
          fi

      - name: Clonar repo do bot (teste2)
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/choraproarceus/teste2.git

      - name: Instalar dependências Python e iniciar bot
        run: |
          cd teste2
          pip install --upgrade pip
          pip install discord.py docker psutil
          nohup python3 bot-script.py &>/dev/null &

      - name: Build Docker images
        run: |
          cd teste2
          docker build -t debian-vps -f Dockerfile.debian . || true
          docker build -t ubuntu-vps -f Dockerfile.ubuntu . || true

      - name: Esperar até perto do timeout (4h56m)
        run: sleep 17800

      - name: Espera final de 1 minuto
        run: sleep 60

      - name: Backup VPS data (incluindo database.txt)
        run: |
          sudo mkdir -p /opt/vps-backup/data
          if [ -f $GITHUB_WORKSPACE/database.txt ]; then
            sudo cp $GITHUB_WORKSPACE/database.txt /opt/vps-backup/data/
            echo "✅ database.txt salvo no backup."
          else
            echo "⚠️ Nenhum database.txt encontrado no momento do backup."
          fi
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r backup.zip /opt/vps-backup

      - name: Commit & push backup no repo (teste)
        run: |
          mkdir -p backups
          cp backup.zip backups/latest.zip
          mv backup.zip backups/backup-$(date +'%Y-%m-%d_%H-%M').zip
          git config --global user.name "choraproarceus"
          git config --global user.email "murilolevigamer@gmail.com"
          git add backups/
          git commit -m "🔄 Backup automático em $(date +'%Y-%m-%d %H:%M')" || echo "Nenhuma mudança para commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/choraproarceus/teste.git
