name: Apolinario

on:
  schedule:
    - cron: '0 */5 * * *'  # Executa a cada 5 horas
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 horas

    steps:
      - name: Checkout repo (teste)
        uses: actions/checkout@v4

      - name: Set hostname to apolinario
        run: sudo hostnamectl set-hostname apolinario

      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Restaurar backup do repo
        run: |
          if [ -f .backups/backup.zip ]; then
            unzip -o .backups/backup.zip -d /
            echo "✅ Backup restaurado do repositório"
          else
            echo "⚠️ Nenhum backup.zip encontrado no repo!"
          fi

      - name: Create user apolinario with sudo
        run: |
          if ! id -u apolinario >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash apolinario
            echo "apolinario:apolinario" | sudo chpasswd
            sudo usermod -aG sudo apolinario
            echo "apolinario ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/apolinario
          fi

      - name: Clone bot repo (teste2)
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/choraproarceus/teste2.git

      - name: Install Python deps and start bot
        run: |
          cd teste2
          pip install --upgrade pip
          pip install discord.py docker psutil
          nohup python3 bot-script.py &>/dev/null &

      - name: Build Docker images
        run: |
          cd teste2
          docker build -t debian-vps -f Dockerfile.debian . || true
          docker build -t ubuntu-vps -f Dockerfile.ubuntu . || true

      - name: Wait until near timeout (4h56m)
        run: sleep 17800

      - name: Sleep final 1 minute
        run: sleep 60

      - name: Backup VPS data (incluindo database.txt)
        run: |
          sudo mkdir -p /opt/vps-backup/data
          if [ -f $GITHUB_WORKSPACE/database.txt ]; then
            sudo cp $GITHUB_WORKSPACE/database.txt /opt/vps-backup/data/
            echo "✅ database.txt salvo no backup."
          else
            echo "⚠️ Nenhum database.txt encontrado no momento do backup."
          fi
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r backup.zip /opt/vps-backup

      - name: Upload VPS backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.zip
